config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'
  get 'welcome/index'
  get 'welcome/about'

  resources :users
  resources :sessions

  #namespace :api, defaults: { format: :json } do
    #resources :users do
      #resources :lists, only: [:create, :update]
    #end

    #resources :lists, only: [:destroy, :index, :show] do
      #resources :items, only: [:create, :update]
    #end
    #resources :items, only: [:destroy, :index, :show]
  #end

  namespace :api, defaults: { format: :json } do
    resources :users do
      resources :lists, only: [:create]
    end

    resources :lists, except: [:create] do
      resources :items, only: [:create]
    end
    resources :items, except: [:create]
  end

  # Sign-In stuff
  get '/signup' => 'users#new'
  post '/users' => 'users#create'
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  mount Knock::Engine => "/knock"

end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :list

  validates :name, presence: true

end

app/models/list.rb
class List < ActiveRecord::Base
  belongs_to :user
  has_many :items

  attr_reader :user

  before_save { self.permission ||= :open }

  validates :title, presence: true

  enum permission: [:open, :viewable, :non_public]

end

app/models/user.rb
require 'bcrypt'

class User < ActiveRecord::Base
  include BCrypt

  has_many :lists

  validates :username, presence: true
  validates :email, presence: true
  validates_presence_of :password, :on => :create

  has_secure_password

end

app/controllers/api/items_controller.rb
class Api::ItemsController < ApiController

  def index
    items = Item.all
    render json: items, each_serializer: ItemSerializer
  end

  def show
    item = Item.find(params[:id])
    render json: item
  end

  def create
    list = List.find(params[:list_id])
    item = list.items.build(item_params)
    if item.save
      render json: item
    else
      render json: { errors: item.errors.full_messages }, status: :unprocessable_entity
    end
  end

  def update
    item = Item.find(params[:id])
    if item.update(item_params)
      render json: item
    else
      render json: { errors: item.errors.full_messages }, status: :unprocessable_entity
    end
  end

  private

  def item_params
    params.require(:item).permit(:name, :completed, :list)
  end


end

app/controllers/api/lists_controller.rb
class Api::ListsController < ApiController

  def index
    lists = List.all
    render json: lists, each_serializer: ListSerializer
  end

  def show
    list = List.find(params[:id])
    render json: list, each_serializer: ListSerializer
  end

  def create
    user = User.find(params[:user_id])
    list = user.lists.build(list_params)
    if list.save
      render json: list
    else
      render json: { errors: user.errors.full_messages }, status: :unprocessable_entity
    end
  end

  def update
    list = List.find(params[:id])
    if list.update(list_params)
      render json: list
    else
      render json: { errors: list.errors.full_messages }, status: :unprocessable_entity
    end
  end

  def destroy
    list = List.find(params[:id])
    if list && list.destroy
      render json: {}, status: :no_content
    else
      render json: {}, status: :not_found
    end
  end

  private

  def list_params
    params.require(:list).permit(:title, :permission, :user)
  end

  def update_validation
    !self.non_public?
  end

end

app/controllers/api/users_controller.rb
class Api::UsersController < ApiController

  def index
    users = User.all
    render json: users, each_serializer: UserSerializer
  end

  def show
    user = User.find(params[:id])
    render json: user
  end

  def create
    user = User.new(user_params)
    if user.save
      render json: user
    else
      render json: { errors: user.errors.full_messages }, status: :unprocessable_entity
    end
  end

  def destroy
    user = User.find(params[:id])
    if user && user.destroy
      render json: {}, status: :no_content
    else
      render json: {}, status: :not_found
    end
  end

  private

  def user_params
    params.require(:user).permit(:username, :email, :password)
  end

end

app/controllers/api_controller.rb
class ApiController < ApplicationController

  include Knock::Authenticable
  skip_before_action :verify_authenticity_token

  before_filter :authenticate
  #before_action :authenticated?

  private

  def authenticated?
    authenticate_or_request_with_http_basic do |username, password|
      #@user = User.find_by_name(params[:name])
      #@user && @user.authenticate(params[:password])
      username == "Caroline" && password == "helloworld"
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include  SessionsHelper
  
  #before_filter :authorize

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user

  def authorize
    redirect_to '/login' unless current_user
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

 def new
 end

 def create
   user = User.find_by_email(params[:email])
   # If the user exists AND the password entered is correct.
   if user && user.authenticate(params[:password])
     # Save the user id inside the browser cookie. This is how we keep the user
     # logged in when they navigate around our website.
     session[:user_id] = user.id
     redirect_to '/'
   else
   # If user's login doesn't work, send them back to the login form.
     redirect_to '/login'
   end
 end

 def destroy
   session[:user_id] = nil
   redirect_to '/'
 end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  attr_accessor :name, :email, :password, :password_confirmation

  def new
    @user = User.new
  end

  def create
    user = User.new(user_params)
    if user.save
      session[:user_id] = user.id
      redirect_to '/'
    else
      redirect_to '/signup'
    end
  end

private

  def user_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def create_session(user)
    session[:user_id] = user.id
  end

  def destroy_session(user)
    session[:user_id] = nil
  end

  def current_user
    User.find_by(id: session[:user_id])
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Open ToDo API</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <div class="container">
    <ul class="nav nav-tabs">
      <li><%= link_to "Home", welcome_index_path %></li>
      <li><%= link_to "About", welcome_about_path %></li>
      <div class="pull-right user-info">
        <div class="pull-right">
          <% if current_user %>
             <%= current_user.username %> | <%= link_to "Sign Out", session_path(current_user), method: :delete %>
          <% else %>
            <%= render 'sessions/login' %>
          <% end %>
        </div>
      </div>
    </ul>

    <div class="flash">
      <% if flash[:notice] %>
        <div class="alert alert-success">
          <button type="button" class="close" data-dismiss"alert">&times;</button>
          <%= flash[:notice] %>
        </div>
      <% elsif flash.now[:alert] %>
        <div class="alert alert-danger">
          <button type="button" class="close" data-dismiss="alert">&times;</button>
          <%= flash.now[:alert] %>
        </div>
      <% elsif flash[:alert] %>
        <div class="alert alert-warning">
          <button type="button" class="close" data-dismiss="alert">&times;</button>
          <%= flash[:alert] %>
        </div>
      <% end %>
    </div>

    <%= yield %>

  </div>

</body>
</html>

app/views/users/_signup.html.erb
<p>New Users: Sign up!</p>
<%= form_for :user, url: '/users' do |f| %>

  Name: <%= f.text_field :username %>
  Email: <%= f.text_field :email %>
  Password: <%= f.password_field :password %>
  Password Confirmation: <%= f.password_field :password_confirmation %>
  <%= f.submit "Submit" %>

<% end %>

app/views/welcome/about.html.erb
<h1>About: Open ToDo API</h1>
<h2>Use Case</h2>

<p>
To-do lists should be simple, while remaining flexible to use.
It's one thing to have a physically limited stack of papers in
your pocket. It's quite another to have a list that works easily
on your Android, and your spouse's iPad, and your Windows
computer (and any command line, worldwide).
</p>

<p>
Apps like <a href="http://todotxt.com">Todo.txt</a> go a long way
towards solving this problem by creating a simple API that any
programmer can easily navigate and extend. Like Todo.txt, this
app will be easy to control from the command line.
</p>

<p>
Your API should allow you to change the same data from the
command line or the browser. This API can support other platforms
and allow programmers to build on your tool in new and exciting
ways.
</p>

app/views/welcome/index.html.erb
<br>
<div class="jumbotron">
  <div class="row">
    <div class="col-md-8">
      <h1>Open ToDo Api</h1>
      <p>Its an API.. get to API'in!</p>
    </div>
    <div class="col-md-4">
      <% if current_user %>
        do stuff
      <% else %>
        <%= render "users/signup" %>
      <% end %>
    </div>
  </div>
</div>